### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by macdipu** [BakingBrains/Pose_estimation#1]
I am getting this error messages:

Traceback (most recent call last):
  File "C:\Users\cdipu\PycharmProjects\PoseEstimationProject\PoseModule.py", line 62, in <module>
    main()
  File "C:\Users\cdipu\PycharmProjects\PoseEstimationProject\PoseModule.py", line 45, in main
    detector = PoseDetector()
  File "C:\Users\cdipu\PycharmProjects\PoseEstimationProject\PoseModule.py", line 18, in __init__
    self.pose = self.mpPose.Pose(self.mode, self.upBody, self.smooth, self.detectionCon, self.trackCon)
  File "C:\Users\cdipu\AppData\Local\Programs\Python\Python39\lib\site-packages\mediapipe\python\solutions\pose.py", line 146, in __init__
    super().__init__(
  File "C:\Users\cdipu\AppData\Local\Programs\Python\Python39\lib\site-packages\mediapipe\python\solution_base.py", line 258, in __init__
    self._input_side_packets = {
  File "C:\Users\cdipu\AppData\Local\Programs\Python\Python39\lib\site-packages\mediapipe\python\solution_base.py", line 259, in <dictcomp>
    name: self._make_packet(self._side_input_type_info[name], data)
  File "C:\Users\cdipu\AppData\Local\Programs\Python\Python39\lib\site-packages\mediapipe\python\solution_base.py", line 513, in _make_packet
    return getattr(packet_creator, 'create_' + packet_data_type.value)(data)
TypeError: create_bool(): incompatible function arguments. The following argument types are supported:
    1. (arg0: bool) -> mediapipe.python._framework_bindings.packet.Packet

Invoked with: 0.5

**Comment by BakingBrains** [comment]
Uninstall mediapipe and install any previous version of mediapipe and try it once.  I think in the latest version some of the modules are changed. Try it and let me know if it runs.

**Comment by macdipu** [comment]
Thanks for your early reply. problem solved by installing mediapipe **0.8.6.2**. However, 0.8.7.0 to 8.8.0 did not work for me.
