### ISSUE TITLE
Invoked with: 0.5

### ISSUE THREAD

**Issue by erikaemma** [BakingBrains/Pose_estimation#4]
```
Downloading model to C:\Users\nobody\anaconda3\lib\site-packages\mediapipe/modules/pose_landmark/pose_landmark_lite.tflite
Traceback (most recent call last):
  File "C:\Users\nobody\Documents\Projects\PycharmProjects\BakingBrains\Pose_estimation\testing_posedetector.py", line 7, in <module>
    detector = pm.PoseDetector()
  File "C:\Users\nobody\Documents\Projects\PycharmProjects\BakingBrains\Pose_estimation\PoseModule.py", line 18, in __init__
    self.pose = self.mpPose.Pose(self.mode, self.upBody, self.smooth, self.detectionCon, self.trackCon)
  File "C:\Users\nobody\anaconda3\lib\site-packages\mediapipe\python\solutions\pose.py", line 146, in __init__
    super().__init__(
  File "C:\Users\nobody\anaconda3\lib\site-packages\mediapipe\python\solution_base.py", line 289, in __init__
    self._input_side_packets = {
  File "C:\Users\nobody\anaconda3\lib\site-packages\mediapipe\python\solution_base.py", line 290, in <dictcomp>
    name: self._make_packet(self._side_input_type_info[name], data)
  File "C:\Users\nobody\anaconda3\lib\site-packages\mediapipe\python\solution_base.py", line 592, in _make_packet
    return getattr(packet_creator, 'create_' + packet_data_type.value)(data)
TypeError: create_bool(): incompatible function arguments. The following argument types are supported:
    1. (arg0: bool) -> mediapipe.python._framework_bindings.packet.Packet

Invoked with: 0.5
```

**Comment by BakingBrains** [comment]
@erikaemma can you try with
`mediapipe==0.8.6.2`

**Comment by erikaemma** [comment]
> @erikaemma can you try with `mediapipe==0.8.6.2 or 0.8.7`

Thank you, 0.8.6.2 work will and 0.8.7 doesn't exist.
